services:
  # client:
  #   container_name: debug_dev_client
  #   build: ./client
  #   image: debug_client
  #   ports:
  #     - 8080:8080
  #   working_dir: /code
  #   volumes:
  #     - type: bind
  #       source: ./client
  #       target: /code
  #   command: ["http-server"]
  api:
    container_name: ark_api
    ports:
      - 3000:3000
    environment:
      - PGUSER=noah
      - PGHOST=db
      - PGPASSWORD=noahsark
      - PGDATABASE=arkives
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: ark_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=arkives
      - POSTGRES_USER=noah
      - POSTGRES_PASSWORD=noahsark
volumes:
  dbdata:
networks:
  default:
    name: ark_api_network
